language: go
go:
  - 1.10.x
  - master

os:
  - linux
  - osx

dist: trusty
sudo: false

install: true

script:
  - env GO111MODULE=on go build 
  - env GO111MODULE=on go test
  - ./httpstat https://dave.cheney.net/
  - ./httpstat https://dave.cheney.net:443/
  - ./httpstat -X POST -d 'post' https://httpbin.org/post
  - ./httpstat -X DELETE https://httpbin.org/delete
  - ./httpstat https://www.google.com/
  - ./httpstat https://www.google.com:443/
  - ./httpstat -L https://httpbin.org/redirect-to?url=https://httpbin.org/relative-redirect/1
  - ./httpstat -I https://httpbin.org/headers
  - ./httpstat -I -L http://httpbin.org/redirect/1
  - ./httpstat https://www.apple.com/
  - ./httpstat -H Accept:\ application/vnd.heroku+json\;\ version=3 https://api.heroku.com/schema
  - ./httpstat -O http://example.com/file && stat file
  - ./httpstat -o custom http://example.com/file && stat custom
  - ./httpstat -O https://httpbin.org/response-headers?Content-Disposition=attachment%3B%20filename%3dtest.json && stat test.json
  - ./httpstat google.com
  - ./httpstat google.com:80
  - ./httpstat google.com:443
  - ./httpstat golang.org:80/dl
  - ./httpstat golang.org:443/dl
  - ./httpstat https://http2.akamai.com/
  - ./httpstat -H Host:\ www.google.com https://$(dig +short www.google.com | head -1):443/
