language: go
go_import_path: github.com/davecheney/httpstat
go:
  - 1.7.1
  - tip

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - dnsutils

sudo: false

install:
  - echo "skipping travis' default go get -t -v to ensure we're only using vendor/ dependencies"

script:
  - go vet $(go list ./... | grep -v "vendor")
  - go build github.com/davecheney/httpstat
  - go test github.com/davecheney/httpstat
  - ./httpstat http://dave.cheney.net/
  - ./httpstat http://dave.cheney.net:80/
  - ./httpstat -X POST -d 'post' http://httpbin.org/post
  - ./httpstat -X DELETE http://httpbin.org/delete
  - ./httpstat https://www.google.com/
  - ./httpstat https://www.google.com:443/
  - ./httpstat -L http://httpbin.org/redirect-to?url=https://httpbin.org/relative-redirect/1
  - ./httpstat -I http://example.com/
  - ./httpstat -I -L http://httpbin.org/redirect/1
  - ./httpstat https://www.apple.com/
  - ./httpstat -H Accept:\ application/vnd.heroku+json\;\ version=3 https://api.heroku.com/schema
  - ./httpstat -O http://example.com/file && stat file
  - ./httpstat -o custom http://example.com/file && stat custom
  - ./httpstat -O http://httpbin.org/response-headers?Content-Disposition=attachment%3B%20filename%3dtest.json && stat test.json
  - ./httpstat google.com
  - ./httpstat google.com:80
  - ./httpstat google.com:443
  - ./httpstat golang.org:80/dl
  - ./httpstat golang.org:443/dl
  - ./httpstat https://http2.akamai.com/
  - ./httpstat -H Host:\ www.google.com https://$(dig +short www.google.com | head -1):443/
