language: go
go_import_path: github.com/davecheney/httpstat
go:
  - 1.7.1
  - tip

sudo: false

install:
  - true

script:
  - go build github.com/davecheney/httpstat
  - ./httpstat http://dave.cheney.net/
  - ./httpstat http://dave.cheney.net:80/
  - ./httpstat https://www.google.com/
  - ./httpstat https://www.apple.com/
